namespace Tanks.Lobby.ClientNavigation.API
{
	public enum LogScreen
	{
		Main = 0,
		Garage = 1,
		Hulls = 2,
		Turrets = 3,
		HullSkins = 4,
		HullPaints = 5,
		TurretSkins = 6,
		TurretPaints = 7,
		HullModules = 8,
		TurretModules = 9,
		TurretShells = 10,
		Graffities = 11,
		ProfileSummary = 12,
		ProfileAccount = 13,
		ShopDeals = 14,
		ShopContainers = 15,
		ShopXCry = 16,
		ShopCry = 17,
		Settings = 18,
		Friends = 19,
		GameModes = 20,
		CustomBattles = 21,
		SearchBattle = 22,
		BattleLobby = 23,
		CreateCustomBattle = 24,
		Battle = 25,
		BattleResultProgress = 26,
		BattleResultQuestsAndRewards = 27,
		BattleResultMatchDetails = 28,
		ShopBlueprints = 29,
		StarterPack = 30,
		ShopPrem = 31,
		GoldBoxes = 32,
	}
}
