namespace Tanks.Lobby.ClientNavigation.API
{
	public enum LogScreen
	{
		Main,
		Garage,
		Hulls,
		Turrets,
		HullSkins,
		HullPaints,
		TurretSkins,
		TurretPaints,
		HullModules,
		TurretModules,
		TurretShells,
		Graffities,
		ProfileSummary,
		ProfileAccount,
		ShopDeals,
		ShopContainers,
		ShopXCry,
		ShopCry,
		Settings,
		Friends,
		GameModes,
		CustomBattles,
		SearchBattle,
		BattleLobby,
		CreateCustomBattle,
		Battle,
		BattleResultProgress,
		BattleResultQuestsAndRewards,
		BattleResultMatchDetails,
		ShopBlueprints,
		StarterPack,
		ShopPrem,
		GoldBoxes
	}
}
