namespace Lobby.ClientPayment.Impl
{
	public enum BankCardType
	{
		AMERICAN_EXPRESS = 0,
		CHINA_UNIONPAY = 1,
		DINERS_CLUB_CARTE_BLANCHE = 2,
		DINERS_CLUB_INTERNATIONAL = 3,
		DINERS_CLUB_UNITED_STATES_AND_CANADA = 4,
		DISCOVERY_CARD = 5,
		INTERPAYMENT = 6,
		INSTAPAYMENT = 7,
		JCB = 8,
		MAESTRO = 9,
		DANKORT = 10,
		NSPK_MIR = 11,
		MASTERCARD = 12,
		VISA = 13,
		UATP = 14,
		VERVE = 15,
		CARDGUARD_EAD_BG_ILS = 16,
		INVALID = 17,
	}
}
