namespace Lobby.ClientPayment.Impl
{
	public enum BankCardType
	{
		AMERICAN_EXPRESS,
		CHINA_UNIONPAY,
		DINERS_CLUB_CARTE_BLANCHE,
		DINERS_CLUB_INTERNATIONAL,
		DINERS_CLUB_UNITED_STATES_AND_CANADA,
		DISCOVERY_CARD,
		INTERPAYMENT,
		INSTAPAYMENT,
		JCB,
		MAESTRO,
		DANKORT,
		NSPK_MIR,
		MASTERCARD,
		VISA,
		UATP,
		VERVE,
		CARDGUARD_EAD_BG_ILS,
		INVALID
	}
}
